layout_spectrum: 0.8970944
typography_spectrum: 0.2093265
color:
  lightness: 0.8213016
  brandStrength: 0.4052657
  saturation: 0.583244
  rhythmicContrast: 0.01933776
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Elska
